### ISSUE TITLE
unsupported operand type(s) for |: 'types.GenericAlias' and 'types.GenericAlias'

### ISSUE THREAD

**Issue by sisrfeng** [tdegeus/GooseBib#63]
Hi, could you help me with this ?
![image](https://user-images.githubusercontent.com/53520949/174464537-23f86c23-4dd5-4c6e-8278-ec3380ee360d.png)

![image](https://user-images.githubusercontent.com/53520949/174464535-87a81924-4e2e-43e5-848f-1b374ebd9ba3.png)

![image](https://user-images.githubusercontent.com/53520949/174464520-0addd2b9-eb04-4b9b-80a9-43e2d5282720.png)

![image](https://user-images.githubusercontent.com/53520949/174464495-5660397b-e9b3-4847-aaf9-904c37062cba.png)

**Comment by tdegeus** [comment]
I think I can: denoting a typing union as `|` [was introduced in Python 3.10](https://docs.python.org/3/library/typing.html#typing.Union) it seems. It is now fixed for older versions in #64 and available in https://github.com/tdegeus/GooseBib/releases/tag/v0.7.0 (available on conda soon)
